language: R
cache: packages

bioc_packages:
  - graph

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
