language: R
cache: packages

before_install:
  - tlmgr install opensans
  - tlmgr install wallpaper
  - tlmgr install eso-pic
  - tlmgr install slantsc
  - tlmgr install fancyhdr
  - tlmgr install hyperref
  - tlmgr install geometry

bioc_packages:
  - graph

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
