language: R
cache: packages

r_github_packages:
  - r-lib/remotes#340

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh
  - Rscript -e 'tensorflow::install_tensorflow(version = "2.1.0")'
  - Rscript -e 'keras::install_keras(tensorflow = "2.1.0")'

script:
  - Rscript faq.R
  - Rscript build.R
  
after_success:
  - ./deploy.sh
