language: R
cache: packages

bioc_packages:
  - graph

r_github_packages:
  - r-lib/remotes#340

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
