language: R
cache: packages

r_github_packages:
  - r-lib/remotes#340

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh
  - Rscript -e 'tensorflow::install_tensorflow()'
  - Rscript -e 'keras::install_keras()'

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
