language: R
cache: packages

r_packages:
  - BiocManager

addons:
  apt:
    packages:
      - libudunits2-dev

before_script:
  - chmod +x ./deploy.sh
  - Rscript -e 'BiocManager::install("CodeDepends", update = FALSE, ask = FALSE)'

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
