language: R
cache: packages

r_packages:
  - clustermq
  - covr
  - forcats
  - ggplot2
  - ggraph
  - lintr
  - pkgdown
  - readxl
  - visNetwork

addons:
  apt:
    packages:
      - libudunits2-dev
      - libzmq3-dev

before_script:
  - chmod +x ./deploy.sh

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
