language: R
cache: packages

r_github_packages:
  - r-lib/remotes#340

before_install:
  - tlmgr install booktabs
  - tlmgr install mdframed
  - tlmgr install xcolor
  - tlmgr install hyperref
  - tlmgr install sourcesanspro

addons:
  apt:
    packages:
      - libudunits2-dev
      - imagemagick

before_script:
  - chmod +x ./deploy.sh
  - R -q -e 'tensorflow::install_tensorflow()'
  - R -q -e 'keras::install_keras()'
  - R -q -e 'install.packages("webshot")'
  - R -q -e 'webshot::install_phantomjs()'

script:
  - Rscript faq.R
  - Rscript build.R
  - ./deploy.sh
